insert into moringpaper(id, parentid, content, link) values('1', '2', 'OPPO Find X3 系列正式发布', 'https://sspai.com/post/65469');
insert into moringpaper(id, parentid, content, link) values('2', '2', '华为 P50 Pro 渲染图曝光', 'https://sspai.com/post/65469');
insert into moringpaper(id, parentid, content, link) values('3', '2', 'Notability 发布新款 macOS 版本', 'https://sspai.com/post/65469');
insert into moringpaper(id, parentid, content, link) values('4', '2', '盒式磁带发明者 Lou Ottens 辞世', 'https://sspai.com/post/65469');
insert into moringpaper(id, parentid, content, link) values('5', '5', '小米 10S 正式发布', 'https://sspai.com/post/65452');
insert into moringpaper(id, parentid, content, link) values('6', '5', '腾讯 ROG 游戏手机 5 系列正式发布', 'https://sspai.com/post/65452');
insert into moringpaper(id, parentid, content, link) values('7', '5', '华为推出 Mate 40E', 'https://sspai.com/post/65452');
insert into moringpaper(id, parentid, content, link) values('8', '5', '文石推出 Nova3 Color 彩屏墨水阅读器', 'https://sspai.com/post/65452');
insert into moringpaper(id, parentid, content, link) values('9', '5', 'Photoshop 正式支持 M1 芯片版 Mac', 'https://sspai.com/post/65452');
insert into moringpaper(id, parentid, content, link) values('10', '5', 'Apple 或推迟新款 MacBook Pro 量产时间', 'https://sspai.com/post/65452');
